apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/ccq18/kadm-platform-system
  newName: ghcr.io/ccq18/kadm-platform-system
  newTag: 20260630060828
